Task/svgiconprovider
s2b/vite-asset-collector pull request #16
Opened 2023-09-13 22:35 UTC by ochorocho

Sorry, messed it up.

This is the origin PR: https://github.com/s2b/vite-asset-collector/pull/9

2023-10-03 16:57 UTC, s2b requested changes

2023-10-03 16:57 UTC, s2b commented on Classes/IconProvider/SvgIconProvider.php
> +            $options['manifest'] ?? $this->extensionConfiguration->get('vite_asset_collector', 'defaultManifest'),
here you can re-use `getManifest()`

2023-10-03 16:57 UTC, s2b commented on README.md
> +To use an icon along with `core:icon` add the following to the `Icons.php` file:
I think that there needs to be a bit more documentation:

* When and why would I want to use this?
* Which adjustments need to be made to vite.config.js?
* Where is this applicable? BE and/or FE?
* A link to [the documentation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Icon/Index.html)

2023-10-03 16:57 UTC, s2b commented on README.md
> +To use an icon along with `core:icon` add the following to the `Icons.php` file:
I can also add this myself after merging.

2023-10-03 21:25 UTC, ochorocho commented on Classes/IconProvider/SvgIconProvider.php
> +            $options['manifest'] ?? $this->extensionConfiguration->get('vite_asset_collector', 'defaultManifest'),
Done :-)

2023-10-05 13:36 UTC, s2b approved these changes

2023-10-05 13:37 UTC, merged